### ISSUE TITLE
should the following test return ture?

### ISSUE THREAD

**Issue by fraserxu** [Dashed/shallowequal#2]
```JavaScript
var equal = require("shallowequal")

var a = { name: 'fraserxu', belongs: ['bike', 'mac'] }
var b = { belongs: ['bike', 'mac'], name: 'fraserxu' }
var c = { belongs: ['bike', 'mac'], name: 'fraserxu' }

console.log(equal(a, b)) // false
console.log(equal(b, c)) // false
```

but if I use substack's [node-deep-equal](https://www.npmjs.com/package/deep-equal)

```JavaScript
var equal = require("deep-equal")

var a = { name: 'fraserxu', belongs: ['bike', 'mac'] }
var b = { belongs: ['bike', 'mac'], name: 'fraserxu' }
var c = { belongs: ['bike', 'mac'], name: 'fraserxu' }

console.log(equal(a, b)) // true
console.log(equal(b, c)) // true
```

Is this the desired behaviour of shallowEqual? Sorry this is not an issue but I'm curious about the difference between `deep` and `shallow` here.

**Comment by Dashed** [comment]
@fraserxu 

> Is this the desired behaviour of shallowEqual? 

In short, this is the desired behaviour of `shallowEqual`.

-----

This is the explanation:

substack's `node-deep-equal` **recursively** traverses objects (and arrays) and when traversal is not possible, values are compared. Thus at the deepest recursion level, strings are compared (example: `a.name === b.name`).

On the other hand, `shallowequal` just traverses only to the ***first*** level, and compare values. The reason why `console.log(equal(a, b))` outputs `false` is because `a.belongs === b.belongs` is `false`. It is `false` because declaring arrays, like `['bike', 'mac']`, creates a new object instance ( since `typeof ['bike', 'mac'] === 'object'`). Internally, `shallowequal` uses strict-equality (i.e. `===`) to compare things.

If an object instance were to be shared between two objects, then we should expect the following to be true:

```js
var equal = require("shallowequal")

var shared_array_reference = ['bike', 'mac'];

var a = { name: 'fraserxu', belongs: shared_array_reference }
var b = { belongs: shared_array_reference, name: 'fraserxu' }

console.log(equal(a, b)) // true
```

----

Also, the order of the keys do not matter, and aren't necessarily guaranteed to be ordered as defined (example: how keys in `a` are defined in a certain order compared to `b` and `c`.)

-----

I hope this clears up any issues on why this is expected behaviour. Let me know if there is something that's not really clear.

**Comment by fraserxu** [comment]
Thanks a lot for the clarification! Much clearer for me now! @Dashed
